### ISSUE TITLE
Odd text rendering issue in dashboard

### ISSUE THREAD

**Issue by jdhirst1** [openshift/console#3959] opened 2020-01-14 18:27 UTC
During testing of OKD4 (4.4.0-0.okd-2020-01-13-234448), I have noticed an odd text rending issue in openshift-console, characters are moving about as the page is scrolled. Noticed in the Status page as shown below, but also shows up in many other places.

Tested in Chrome for Linux x64 78.0.3904.108 (Official Build).

I don't have other machines to test with, can we see if this is reproducible?

EDIT: Just tested Firefox 72.0.1 on Linux x64, no issues there. Issue seems to be Chrome-specific.

![DeepinScreenshot_select-area_20200114131357](https://user-images.githubusercontent.com/9157196/72371067-93906500-36d1-11ea-9182-9141c2575cc4.png)

**Comment by spadgett** [comment] 2020-02-03 16:54
/kind bug
/assign @rawagner 

@rhamilto @sg00dwin fyi in case you've seen this

**Comment by rawagner** [comment] 2020-02-04 09:14
I cant reproduce on chrome 78.0.3904.108 or 79. Is it happening only on dashboards page or on others too ? Can you try with chrome 79 too ?

**Comment by jdhirst1** [comment] 2020-02-05 17:37
I think this can be closed as I noticed the same issue when browsing the Openshift documentation site on this system. It seems to be something with text rendering for the font that's used, however I'm not quite sure.

**Comment by spadgett** [comment] 2020-05-11 20:05
> I think this can be closed as I noticed the same issue when browsing the Openshift documentation site on this system. It seems to be something with text rendering for the font that's used, however I'm not quite sure.

Thanks for the update. Closing for now.

/close

**Closed** 2020-05-11 20:06 UTC
Labels: component/dashboard, kind/bug
