### ISSUE TITLE
Why is there no OpenShift version on the Help > About page on the Web Console

### ISSUE THREAD

**Issue by mandibuswell** [openshift/console#8220] opened 2021-02-23 08:05 UTC
Steps to Reproduce:
In 4.x, from the OpenShift Web Console, select the ? dropdown from the top right. 
Select ABOUT to display the About popup window.

The text here shows only the Kubernetes Version, and API Server URL for this cluster.

Issue:
In 3.x under about it was possible to see the OpenShift version as it was listed specifically.
There is no easy way without reviewing documentation, to find the mapping between k8s version and OCP version anymore since 4.x. 
As an admin user, I would go to the Cluster Settings page to find the OpenShift version, but as a Developer user I do not have access to the Cluster Settings page.

I see in the source code, assuming this is the correct page https://github.com/openshift/console/blob/052f2478025daa0f56c23aa7e7364198ca555ab9/frontend/public/components/about-modal.tsx, that it looks like there is the code to display the OpenShift version but I have never seen this displayed on any version of a 4.x cluster.

Is there actually a bug here? If not, I would like to know if we could put back in the OpenShift version number under the Help > About  Web Console popup.

**Comment by TheRealJon** [comment] 2021-03-08 22:07
Unable to reproduce this on latest. Is there a specific version or versions you are seeing this in?

**Comment by TheRealJon** [comment] 2021-03-08 22:08
Ping @mandibuswell, forgot to mention you in that last comment.

**Comment by beloyar777** [comment] 2021-05-25 22:16
@TheRealJon I can reproduce it in OpenShift 4.6.20

**Comment by beloyar777** [comment] 2021-05-25 22:42
@TheRealJon As said here https://github.com/openshift/console/issues/5606#issuecomment-636946993
"You currently need authority to see the ClusterVersion resource to get the OpenShift version."

**Comment by mandibuswell** [comment] 2021-05-26 00:29
@TheRealJon  yes it is the same issue as seen in https://github.com/openshift/console/issues/5606

**Comment by TheRealJon** [comment] 2021-07-07 19:01
Closing as duplicate of #5606

**Closed by TheRealJon** 2021-07-07 19:01 UTC
Labels: component/core, kind/bug
