### ISSUE TITLE
Default view for different users

### ISSUE THREAD

**Issue by wjiangjay** [openshift/console#1320] opened 2019-03-22 08:50 UTC
Hi:

Do we have any concerns to decide which page should be the default page after user(include cluster-admin) login to improve UX?

For me, if I am a ops permissions user, I prefer to a whole dashboard show out after I login, like /overview/all-namespaces page.

And for normal user without enough permissions, I prefer to show the dashboard after I click a project name instead of a resource list.

How do you think?

**Comment by spadgett** [comment] 2019-03-27 21:54
I agree the cluster status page would be a better default for cluster admins. The problem is that we don't want to block load on the self subject access review request to check permissions. We'd have to investigate whether there's a good way around that.

**Comment by christianvogt** [comment] 2019-06-07 12:23
Consider server side check for first load.
We should also look at user settings. In the interim save them to local storage and let the user choose their landing page.

**Comment by spadgett** [comment] 2019-08-10 13:35
We've changed the default page to the cluster dashboards for cluster admins in #2008. We've changed the default project page to the project dashboard in #1694. This is addressed in 4.2.

/close

**Closed by spadgett** 2019-08-10 13:35 UTC
Labels: triage/support
