### ISSUE TITLE
Topology page exist performance problems

### ISSUE THREAD

**Issue by klzsysy** [openshift/console#10337] opened 2021-10-27 08:13 UTC
Hello:  
      If the namespace exists more resources，When I opened the topology page list mode， Loading is very slow，Sometimes crash

example ： 
https://console.xxx.com/topology/ns/app?view=list

![image](https://user-images.githubusercontent.com/3226923/139025429-5da24250-b1ac-49cd-9787-df460986aa3b.png)

The namespace exist 51 dc
```shell
➜  ~ oc -n app get dc | wc
     51     256    4384

➜  ~ oc -n app get svc | wc
     37     222    3442

➜  ~ oc -n app get pod | wc

➜  ~ oc version
Client Version: 4.8.0-0.okd-2021-10-24-061736
Server Version: 4.8.0-0.okd-2021-10-24-061736
Kubernetes Version: v1.21.2-1505+6438632813d726-dirty
```

**Comment by AlexFilimonov** [comment] 2021-11-03 18:57
We have the same issue. Project has around 30 deployments and deployments config.

```
oc get deployment,deploymentconfig -n xxx -o name | wc -l
33
```

Users faced with low performance, stuck of console, crush in both Graph view and List view.
```
OpenShift version    4.7.0-0.okd-2021-08-22-163618
Kubernetes version    v1.20.0-1093+4593a24e8fd58d-dirty
Channel    stable-4
```

**Comment by spadgett** [comment] 2021-11-15 13:02
cc @rohitkrai03 @christianvogt

**Comment by christianvogt** [comment] 2021-11-15 18:49
fyi @jerolimov, since you're currently assigned a jira story on topology performance

**Comment by jerolimov** [comment] 2021-11-16 19:00
Hi @klzsysy, hi @AlexFilimonov,

thanks for reporting this. We currently looking into general topology performance issues. We couldn't reproduce a browser tab crash yet and will check that as well.

* Can you share some info about your browser?
* It's Chrome, right? On which OS?
* How much RAM does your computer have?
* Have you multiple tabs open with the console or just this tab?
* You have around 50 DeploymentConfigs and over 35 Knative Services, right? Any other infos you can share about your cluster or this namespace? How many pods are running? Maybe this helps as well.

Thank you.

Currently, we expect that this will be part of one of the upcoming updates. As workaround you can try the list view. I know this is less than half as cool as the graph view.

**Comment by klzsysy** [comment] 2021-11-17 04:15
- yes, it's chrome
- macos 11.5.1, M1 macbook Air, 8G RAM
- test safari same effect, page crash or freeze
- browser single tabs same effect
- The namespace only dc, svc, pod
- Is already list view， but same

if dc include label "app.kubernetes.io/part-of"，page seem load more slowly

```shell
❯ oc -n app get dc | wc
      96     481    8318
❯ oc -n app get svc | wc
      37     222    3441
❯ oc -n app get pod | wc
      90     450    6840

#  Please ignore the CrashLoopBackOff pod
 oc -n app get pod
NAME                              READY   STATUS             RESTARTS   AGE
academy-v1-4-0-1-4pdfh            2/2     Running            0          24h
academy-v1-4-0-1-j5sl9            2/2     Running            0          25h
analyze-v0-4-1-21-ksgzz           1/2     CrashLoopBackOff   292        24h
analyze-v0-4-1-21-zcgx4           1/2     CrashLoopBackOff   294        25h
assistant-v1-25-1-1-5pj8t         1/2     CrashLoopBackOff   296        24h
assistant-v1-25-1-1-fb5jp         1/2     CrashLoopBackOff   300        25h
assistant-v1-25-1-1-r8nbw         1/2     CrashLoopBackOff   305        25h
assistant-v1-30-0-1-deploy        0/1     Error              0          17h
certificate-v1-4-1-13-jzrsd       2/2     Running            0          25h
clearing-v1-3-0-15-p27xn          1/2     CrashLoopBackOff   291        24h
clearing-v1-3-0-15-xmcv6          1/2     CrashLoopBackOff   290        24h
community-v1-7-3-11-frlrh         2/2     Running            0          25h
contract-v1-1-0-11-59pvn          1/2     CrashLoopBackOff   287        24h
contract-v1-1-0-11-8xcvz          1/2     CrashLoopBackOff   295        25h
coupon-15-8gbmj                   1/2     CrashLoopBackOff   291        24h
coupon-15-k4t89                   1/2     CrashLoopBackOff   300        25h
course-v1-1-0-11-g92xl            2/2     Running            0          25h
course-v1-1-0-11-qmvwf            2/2     Running            0          25h
evaluating-9-8qj78                2/2     Running            0          24h
evaluating-9-cqdzj                2/2     Running            0          25h
fid-v0-6-6-7-45l8j                2/2     Running            0          24h
fid-v0-6-6-7-9h6gk                2/2     Running            0          25h
goods-15-cwhdn                    2/2     Running            0          25h
goods-15-pxvtn                    2/2     Running            0          25h
jinshuju-v1-4-5-9-5l6f7           2/2     Running            0          24h
jinshuju-v1-4-5-9-bzxf2           2/2     Running            0          24h
license-v1-0-4-15-2sr9n           2/2     Running            0          25h
license-v1-0-4-15-slxd5           2/2     Running            0          24h
marketing-v1-2-7-13-kfdbc         1/2     CrashLoopBackOff   299        25h
marketing-v1-2-7-13-smbg7         1/2     CrashLoopBackOff   297        24h
mp-wx-user-v0-4-3-17-hxcp6        1/2     CrashLoopBackOff   278        25h
mp-wx-user-v0-4-3-17-nvj5t        1/2     CrashLoopBackOff   271        25h
mp-wx-v0-2-1-13-t66jh             2/2     Running            0          24h
notice-v0-1-0-11-ktlf9            1/2     CrashLoopBackOff   302        25h
notice-v0-1-0-11-v2l5c            1/2     CrashLoopBackOff   297        24h
order-v1-3-0-11-dg4xv             1/2     CrashLoopBackOff   292        24h
order-v1-3-0-11-p4ktm             1/2     CrashLoopBackOff   303        25h
product-v1-4-1-9-8zdxq            1/2     CrashLoopBackOff   303        25h
product-v1-4-1-9-nt9w6            1/2     CrashLoopBackOff   291        24h
py-order-v0-2-1-7-9bbtt           2/2     Running            0          24h
receiving-order-v1-1-0-7-6btnp    2/2     Running            0          24h
receiving-order-v1-1-0-7-6r6cm    2/2     Running            0          24h
receiving-order-v1-1-0-7-nsm9m    2/2     Running            0          25h
sandbox-v1-2-12-7-8d7nx           2/2     Running            0          25h
sandbox-v1-2-12-7-xt5qp           2/2     Running            0          24h
scrm-v1-0-0-3-qgvlq               2/2     Running            0          25h
scrm-v1-2-0-1-deploy              0/1     Error              0          17h
secode-v0-2-4-14-cctzd            1/2     CrashLoopBackOff   209        24h
secode-v0-2-4-14-sspnr            1/2     CrashLoopBackOff   208        24h
survey-v1-10-0-1-r7tfb            2/2     Running            0          25h
survey-v1-10-0-1-zgszl            2/2     Running            0          24h
teacher-v1-5-7-1-deploy           0/1     Error              0          20h
timeline-v1-6-0-1-2ms94           1/2     CrashLoopBackOff   217        25h
timeline-v1-6-0-1-lcmqh           1/2     CrashLoopBackOff   208        24h
uac-v1-13-5-1-7zb97               2/2     Running            0          25h
uac-v1-13-5-1-8tjqr               2/2     Running            0          24h
wind-wechat-ps-v1-4-0-1-deploy    0/1     Completed          0          17h
wind-wechat-ps-v1-4-0-1-wjfvs     2/2     Running            0          17h
wind-wechat-v1-26-0-d2-4-phnq7    1/2     CrashLoopBackOff   294        24h
wind-wechat-v1-26-1-7-deploy      0/1     Error              0          95m
wind-wechat-v1-26-1-d1-3-s888c    1/2     CrashLoopBackOff   302        25h
wind-wechat-v1-26-1-d1-5-deploy   0/1     Error              0          94m
wind-wechat-v1-26-1-d2-6-b5qhc    1/2     CrashLoopBackOff   23         94m
wind-wechat-v1-26-1-d2-6-deploy   0/1     Completed          0          94m
wind-wechat-v1-26-2-d1-3-zxm8p    1/2     CrashLoopBackOff   296        24h
wind-wechat-v1-26-2-d2-5-8jjwl    1/2     Error              302        25h
wind-wechat-v1-27-0-d2-3-rp67b    1/2     CrashLoopBackOff   291        24h
wind-wechat-v1-28-0-d1-2-4nm2w    1/2     CrashLoopBackOff   301        25h
wind-wechat-v1-28-1-d1-1-nvph2    1/2     CrashLoopBackOff   301        25h
wind-wechat-v1-28-1-d2-2-46qtk    1/2     CrashLoopBackOff   291        24h
wind-wechat-v1-29-0-3-deploy      0/1     Error              0          17h
wind-wechat-v1-29-0-d1-1-cv569    1/2     CrashLoopBackOff   296        24h
wind-wechat-v1-29-0-d1-2-deploy   0/1     Error              0          17h
wind-wechat-v1-29-0-d2-3-deploy   0/1     Completed          0          17h
wind-wechat-v1-29-0-d2-3-k6l9p    1/2     CrashLoopBackOff   213        17h
wind-wechat-v1-30-0-1-deploy      0/1     Error              0          17h
wind-wechat-v1-30-0-3-deploy      0/1     Error              0          95m
wind-wechat-v1-30-0-d1-1-5cls5    1/2     CrashLoopBackOff   213        17h
wind-wechat-v1-30-0-d1-1-deploy   0/1     Completed          0          17h
wind-wechat-v1-30-0-d1-3-deploy   0/1     Error              0          95m
wind-wechat-v1-30-0-d2-1-deploy   0/1     Completed          0          17h
wind-wechat-v1-30-0-d2-3-deploy   0/1     Completed          0          95m
wind-wechat-v1-30-0-d2-3-dkh6h    1/2     CrashLoopBackOff   23         95m
wind-wechat-v1-30-1-1-deploy      0/1     Error              0          95m
wind-wechat-v1-30-1-d1-1-deploy   0/1     Error              0          95m
wind-wechat-v1-30-1-d2-1-deploy   0/1     Completed          0          95m
wind-wechat-v1-30-1-d2-1-lnbn8    1/2     CrashLoopBackOff   23         95m
wind-wxb-v1-0-6-13-c8j4r          1/2     CrashLoopBackOff   304        25h
yiye-v0-12-2-9-p45hn              2/2     Running            0          24h
```

**Comment by jerolimov** [comment] 2021-11-17 07:34
Thanks for all these details. We look into this

**Comment by AlexFilimonov** [comment] 2021-11-17 13:16
Hi @jerolimov 
1. Windows 10 Pro 21H1 with Firefox 94.0.1
2. Intel(R) Core(TM) i5-1145G7/32 GB
3. Both, with other tabs or single topology page
4. Some details
**Deployments, DeploymentConfigs**
`oc get deployment,dc | wc -l
72
`
**Pods**
` oc get pod | grep Running | wc -l
52
`
**Services**
`oc get svc | wc -l
103
`
Topology tab consumes around 1GB memory and 10-15% CPU.

**Closed** 2022-07-17 07:12 UTC
Labels: kind/bug, lifecycle/rotten, component/topology
